#! /bin/bash
set -e

if [[ $# -lt 1 || $# -gt 2 ]] ; then
	echo "Usage: $0 <nginx-version> [1]" 1>&2
	exit 1
fi

readonly NGINX=$1

if [[ $2 -eq 1 ]] ; then
	readonly DYNAMIC=$2
fi

cd "$(dirname "$0")/.."
[[ -f nginx-${NGINX}.tar.gz ]] || wget http://nginx.org/download/nginx-${NGINX}.tar.gz
[[ -d nginx-${NGINX} ]] && rm -r nginx-${NGINX}
tar -xzf nginx-${NGINX}.tar.gz
rm -rf prefix/
cd nginx-${NGINX}
./configure \
	--with-compat \
    --with-debug \
    --with-ipv6 \
    --with-pcre-jit \
    --with-file-aio \
    --with-mail \
    --with-mail_ssl_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-threads \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_dav_module \
    --with-http_gzip_static_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_xslt_module \
    --with-http_image_filter_module \
    --with-http_sub_module \
    --with-http_v2_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-threads \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_slice_module \
    --with-http_degradation_module \
    --with-http_geoip_module \
    --with-http_gunzip_module \
    --with-http_auth_request_module \
	--prefix="$(pwd)/../prefix"
make install
cd ..
rm -r nginx-${NGINX}
tar -xzf nginx-${NGINX}.tar.gz
cd nginx-${NGINX}
./configure \
	--with-compat \
	--add-${DYNAMIC:+dynamic-}module=.. \
	--with-http_addition_module \
	--prefix="$(pwd)/../prefix"
make modules
mkdir "$(pwd)/../prefix/modules"
cp objs/*.so "$(pwd)/../prefix/modules"
cd ..
exec ./t/run prefix ${DYNAMIC}
